name: Update README

on:
  schedule:
    - cron: '0 */12 * * *'  # Cada 12 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4  # Versión actualizada

      - uses: Readme-Workflows/recent-activity@v5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Funcionará con los permisos
          COMMIT_MSG: "Actualizada actividad reciente"
          MAX_LINES: 8  # Límite de actividades a mostrar
